name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: maik-hasler/Workflows/.github/workflows/build.yml@main
    with:
      dotnet-version: 8.0.x
      project-path: 'NFunctional.sln'